const actionTypes = {
    GET_FLOOR: "GET_FLOOR",
    GET_SUBJECTLIST: "GET_SUBJECTLIST",
    GET_SUBJECT: "GET_SUBJECT",
    GET_ASSIGNLIST: "GET_ASSIGNLIST",
    GET_ASSIGNMENT: "GET_ASSIGNMENT",
    LIKE: "LIKE",
    ADD_COMMENT: "ADD_COMMENT",

    ACTIVATE_POPUP: "ACTIVATE_POPUP",
    CLOSE_POPUP: "CLOSE_POPUP",
};

export default actionTypes;
