const actionTypes = {
    GET_FLOOR: "GET_FLOOR",
    GET_SUBJECTLIST: "GET_SUBJECTLIST",
    GET_ASSIGNLIST: "GET_ASSIGNLIST",
    GET_ASSIGNMENT: "GET_ASSIGNMENT",
    LIKE: "LIKE",
    ADD_COMMENT: "ADD_COMMENT",
};

export default actionTypes;
